name: BACKEND-CI

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main

jobs:
  cs-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"
          extensions: gd bcmath zip

      - uses: php-actions/composer@v6
        with:
          php_version: "8.4"
          php_extensions: gd bcmath zip
      - run: |
          php vendor/bin/phpcs --standard=PSR12 --warning-severity=0 src tests

  dependencies-security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"
          extensions: gd bcmath zip

      - uses: php-actions/composer@v6
        with:
          php_version: "8.4"
          php_extensions: gd bcmath zip

      - name: Run dependencies security check
        uses: php-actions/composer@v6
        with:
          command: audit

  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"
          extensions: gd bcmath zip

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - uses: php-actions/composer@v6
        with:
          php_version: "8.4"
          php_extensions: gd bcmath zip

      - name: Run phpunit
        run: |
          php vendor/bin/phpunit tests/

